os: osx
language: objective-c
xcode_workspace: Monal/Monal.xcworkspace
xcode_scheme: Monal
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
osx_image: xcode11.2
podfile: Monal/Podfile
before_install:
  - cd Monal
  - gem install cocoapods --pre
  - pod install --repo-update
