os: osx
language: objective-c
xcode_workspace: Monal/Monal.xcworkspace
xcode_scheme: Monal
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPad Pro (9.7-inch)
osx_image: xcode11.2
podfile: Monal/Podfile
