name: push-tests

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
    branches-ignore:
      - 'develop'
      - 'alpha.build'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Checkout submodules
        run: git submodule update --remote
      - name: Run tests
        run: |
          cd Monal
          pod install
          xcodebuild -workspace "Monal.xcworkspace" -scheme "Monal" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro' test
